# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: default
  vmImage: vm20561

steps:
- task: CmdLine@1
  inputs:
    script: 'git clone https://Syncfusion-Javascript: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@github.com/essential-studio/nuget_automation -b Azure'
    workingDirectory: 'C:\Automation'  
- task: CmdLine@2
  inputs:
    script: $(FinalBuilderExe) $(FinalBuilderProject) $(Argument)
    workingDirectory: 'C:\Automation\nuget_automation\Testing Automation\Online Testing Automation'
