
name: gitleaks
on:
  public
jobs:
  scan:
    name: gitleaks
    runs-on: windows-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
          fetch-depth: 0
     - name: Get the dir
       run: |
         dir
     - name: Install the gitleaks
       run: ./install.ps1
       shell: pwsh
     - name: Generate the report
       run: D:\gitleaks\gitleaks.exe detect -s D:\a\ES-repository1\ES-repository1 -f json -r D:\a\ES-repository1\ES-repository1\gitleaksreport.json
       shell: pwsh
