name: detect secret

on:
  public

jobs:
  add_assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: dfas
          assignees: kanna
